apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: hello-world-template
spec:
  type: url
  target: https://raw.githubusercontent.com/aizuddin85/backstage-app1/main/hello-world/template.yaml

